package com.rafaeltmbr.stopwatch.platform.presentation.compose.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF004E97)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD5E3FF)
val onPrimaryContainerLight = Color(0xFF001B3C)
val secondaryLight = Color(0xFF29638A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCBE6FF)
val onSecondaryContainerLight = Color(0xFF001E30)
val tertiaryLight = Color(0xFF6F5675)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFDC2C2)
val onTertiaryContainerLight = Color(0xFF28132F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFEDEFF1)
val onBackgroundLight = Color(0xFF191C20)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF171C1F)
val surfaceVariantLight = Color(0x330084FF)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797A)
val outlineVariantLight = Color(0xFFBFC8CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3134)
val inverseOnSurfaceLight = Color(0xFFEDF1F5)
val inversePrimaryLight = Color(0xFFA8C8FF)
val surfaceDimLight = Color(0xFFD6DBDE)
val surfaceBrightLight = Color(0xFFF5FAFD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F7)
val surfaceContainerLight = Color(0xFFEAEEF2)
val surfaceContainerHighLight = Color(0xFFE4E9EC)
val surfaceContainerHighestLight = Color(0xFFDEE3E6)

val primaryDark = Color(0xFF005CB9)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF254777)
val onPrimaryContainerDark = Color(0xFFD5E3FF)
val secondaryDark = Color(0xFF97CCF8)
val onSecondaryDark = Color(0xFF00344F)
val secondaryContainerDark = Color(0xFF004B71)
val onSecondaryContainerDark = Color(0xFFCBE6FF)
val tertiaryDark = Color(0xFFDBBCE1)
val onTertiaryDark = Color(0xFF3E2845)
val tertiaryContainerDark = Color(0xFF651C1C)
val onTertiaryContainerDark = Color(0xFFF8D8FE)
val errorDark = Color(0xFFFF6E5D)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE1E2E9)
val surfaceDark = Color(0x11FFFFFF)
val onSurfaceDark = Color(0xFFDEE3E6)
val surfaceVariantDark = Color(0x880084FF)
val onSurfaceVariantDark = Color(0xFFBFC8CA)
val outlineDark = Color(0xFF899294)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E6)
val inverseOnSurfaceDark = Color(0xFF2C3134)
val inversePrimaryDark = Color(0xFF3F5F90)
val surfaceDimDark = Color(0xFF0F1417)
val surfaceBrightDark = Color(0xFF353A3D)
val surfaceContainerLowestDark = Color(0xFF0A0F11)
val surfaceContainerLowDark = Color(0xFF171C1F)
val surfaceContainerDark = Color(0xFF1B2023)
val surfaceContainerHighDark = Color(0xFF252B2D)
val surfaceContainerHighestDark = Color(0xFF303638)





